#数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: test
    driver-class-name: com.mysql.jdbc.Driver
